### ISSUE TITLE
Custom TCP Port for DoT

### ISSUE THREAD

**Issue by ebal** [kkk669/DNSecure#11]
Hi,

this is a feature request on having an extra field to declare an alternate TCP Port for DoT servers. Although the majority and default port is 853 a lot of providers are blocking this port or sometimes a DoT server have a different functionality to another tcp port. So it would be useful to have the opportunity to declare an custom port to a different field (if necessary) 

PS: Thanks for this project

**Comment by kkk669** [comment]
As far as I know, changing TCP port for DoT isn't supported by [Apple's API](https://developer.apple.com/documentation/networkextension/dns_settings).

Instead, I recommend you use DNS over HTTPS in that case. DNSecure also supports DNS over HTTPS.

**Comment by ebal** [comment]
Hey,
if there isnt a way in iOS then I guess it is okay to close this issue/feature request.

Yes we are also using DoH. In DoH you can declare a different functionality by using a different endpoint in the same domain/IP. Unfortunately in DoT the majority of clients are connected directly to the IP:PORT thus making it difficult to provide an additional functionality other the default.

**Comment by kkk669** [comment]
Thanks.

DoT support in iOS is always use TCP 853 port according to https://developer.apple.com/documentation/networkextension/nednsovertlssettings/3552332-servername.

> In DoH you can declare a different functionality by using a different endpoint in the same domain/IP.

You can specify any endpoint here.
![E87D955A-0AFC-4070-AEAF-A0452EED5BD8](https://user-images.githubusercontent.com/601636/96372356-63667d00-11a1-11eb-87a2-491b09da04ff.jpeg)

However, the endpoint must follow RFC 8484; the other formats, e.g. JSON API, are not supported by [iOS](https://developer.apple.com/documentation/networkextension/nednsoverhttpssettings/3552330-serverurl).

**Comment by ebal** [comment]
yes, we know 

We wrote an article for this: 
https://libreops.cc/2020/10/14/libredns-ios/

:)

**Comment by kkk669** [comment]
Awesome! If there's anything I can do to help, please feel free to open a new issue.
