### ISSUE TITLE
Remove error constantly appearing

### ISSUE THREAD

**Issue by aalmenar** [kkk669/DNSecure#12]
With the new update changing the name or adding dns addresses or whatever make it a pain with an error constantly appearing.

Sample included in video.

https://twitter.com/aalmenar/status/1317819504882307072

**Comment by kkk669** [comment]
Thanks for reporting. I reproduced the issue.

The workaround is to edit configuration after one of servers' "Use This Server" option is turned on.

**Comment by kkk669** [comment]
A fix for this bug will be shipped in DNSecure 1.0.3. The update for [TestFlight](https://testflight.apple.com/join/A8GwCnq8) is going to be released in a few days, and for App Store later.
