### ISSUE TITLE
Feature: configuration templates

### ISSUE THREAD

**Issue by kkk669** [kkk669/DNSecure#13]
Currently, DNSecure has the examples of DNS services by default, e.g. Google Public DNS, Cloudflare 1.1.1.1, and Quad9.

However, it has the following problems:

1. Once you change server settings, you can't see a new default list even if you update the app that includes a new one.
1. If the default list is too long, the app becomes less useful.
    - Related to https://github.com/kkk669/DNSecure/pull/10#issuecomment-711444467

To solve them, I plan to treat those DNS services as templates and add "Create from Templates" into the context menu of the plus button so that I can leave the default list empty.

**Comment by kkk669** [comment]
Moved to #23

**Comment by nitrohorse** [comment]
Hi, thanks for developing this app; it’s really useful! Please feel free to use any premade configurations I created at https://gitlab.com/nitrohorse/ios14-encrypted-dns-mobileconfigs/-/tree/master/mobileconfig. Would be neat to eventually have that list of providers predefined in the app for even more convenience for users but of course UX and maintainability need to be considered.

**Comment by zero0ID** [comment]
Hello,
now I have a peculiar question. 
What to use, your app @kkk669, which from v1.1.1 is working flawlessly or profile files as made by @nitrohorse?
I mean are there some advantages or disadvantages between those two approaches?
With the app its much easier to change the servers, but once settled for an server the changes are scarce...

Thank you both for excellent job done for free!

-0ID

9 Jan 2021, 01:02 by notifications@github.com:

**Comment by nitrohorse** [comment]
I think an app like DNSecure is more advantageous than a mobileconfig due to:
- The ability to change a configuration in the app instead of needing to re-download/install the mobileconfig. Depending on the server's organization/maintainer, changes may be infrequent, yes. But where there is a change, users need to either depend on the mobileconfig maintainer (e.g. myself) to keep it up to date and re-download or change it themselves and re-download. DNSecure simplifies the steps needed to get reconnected when that scenario occurs. 🤔

**Comment by zero0ID** [comment]
Hello All,

Bellow is Thomas, the admin of UncensoredDNS, reply with the screenshot how the rootcanary.org DNSSEC Unicast Denmark test should look (att. A). I get always such result when I config manually on iPad or iPhone the DNS severs in WiFi > my SSID > i > Configure DNS > Manual.

When using the NitroHorse Unicast downloaded profiles or Kubo-san app with Unicast DoH or DoT enabled, I get different results (att. DoH and att. DoT)

So definitively, there is a problem, but no idea where... Didnt make Apple some changes on 14.3?

Sorry for ruining your Sunday

Vlado


-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


Date: 10 Jan 2021, 00:19
From: admin@censurfridns.dk
To: 0id@tutamail.com
Subject: Re: Unicast problem?


>
> Hello
>
>
> Rootcanary is supposed to look like the attached image. It looks      like you may be speaking to some other server? Not sure how to      explain it.
>
>
> All the censurfridns/uncensoreddns servers support DNSSEC and      have done so since the very beginning back in 2009 :)
>
>
> Best regards,
>
>
>
>
> Thomas Steen Rasmussen
>  censurfridns
>
>
>
>
>
>
> On 1/8/21 3:36 PM, zerøID wrote:
>
>> Hi Thomas
>> I startet to use DoH and DoT protocols for the Unicast        server, but something is unclear.
>> When testing the configuration setting on >> https://rootcanary.org/ <https://rootcanary.org/test.html>>>  page        I get random results. According to Roland, the admin of        RootCanary, the possible cause is that there are mores servers        involved, some supporting DNSSEC, some not...
>>
>> Thank you for support
>>
>> Vlado
>>
>>
>>
>> -- 
>> Sent with Tutanota, the secure & ad-free mailbox: 
>> https://tutanota.com
>>

**Comment by kkk669** [comment]
Hi @zero0ID,

Anyway, the discussion is not related to this issue #13, so could you please open a new issue? Thanks.

**Comment by zero0ID** [comment]
Sorry, but I don't have your email address -:(

-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


10 Jan 2021, 10:21 by notifications@github.com:

**Comment by kkk669** [comment]
No, it's not an email. You can open a new issue on [GitHub](https://github.com/kkk669/DNSecure/issues/new).
