### ISSUE TITLE
Add LibreDNS

### ISSUE THREAD

**Issue by comzeradd** [kkk669/DNSecure#14]
Following up from #10 [we](https://libredns.gr/) would love if we could be part of this list, since many of our users use your app (great work btw :heart:). But I understand that you don't want the providers list to go huge, so I thought I should ask before we open a PR.

If you plan to make UI changes in the sidebar to accommodate more providers, one idea is to group per provider since some of them may have different protocols (DoH, DoT) or options (cutting ads, trackers, etc).

**Comment by kkk669** [comment]
I plan to remove the default examples and make it possible to select a server from templates instead. Please see #13. It is scheduled for 1.2.0 or 2.0.0.

But until then, I'll basically merge a PR like #10. So, feel free to send me a PR. Thank you.

> many of our users use your app (great work btw ❤️)

Awesome!

**Comment by aalmenar** [comment]
Wouldn't be a better way to have an option to download configs using a json published in this repository, to list and download and add them to dnsecure ?

Something like "DNS Security" app did on theirs like:

https://raw.githubusercontent.com/peterlee0127/DNS-Security-iOS/main/config.json
