### ISSUE TITLE
request for mobileconfig

### ISSUE THREAD

**Issue by csousougen** [kkk669/DNSecure#25]
Hey, thanks for your nice work!
Since your app is not available for Mac yet, could you please share a mobileconfig that could be used in Mac?
I need a profile that is system-wide and not used only by Safari. I cannot find it elsewhere.

Thanks

**Comment by kkk669** [comment]
Thank you for an idea. Could you please post a feature request on [Discussions](https://github.com/kkk669/DNSecure/discussions) instead of Issues? Thanks.
