### ISSUE TITLE
Settings changes from DNSecure to Automatic when new server select

### ISSUE THREAD

**Issue by zero0ID** [kkk669/DNSecure#28]
Also a warning message shows up when changes are made #

![8AC96006-42F7-4743-BB52-204E5EA74775](https://user-images.githubusercontent.com/76554148/103079467-3173fb80-45d4-11eb-820d-285668bd5895.png)

**Comment by kkk669** [comment]
@zero0ID Is this the same problem as #29? If not, could you be more specific about the steps to reproduce the problem?
