### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by kkk669** [kkk669/DNSecure#34]
Technically, DNSecure is possible to support macOS. I'm currently working on this.

**Comment by kkk669** [comment]
Though I haven't committed the completed code, the app works on macOS. However, I couldn't enable it on System Preferences. I don't know why.

https://developer.apple.com/forums/thread/671196

**Comment by zero0ID** [comment]
Isn't that the app don't have full access to "all files" or something similar?
Good info sources for such settings are the eclecticlight.co and mrmacintosh.com

**Comment by crcastle** [comment]
@kkk669 are you using LuLu or another app that uses Apple's [NetworkExtension](https://developer.apple.com/documentation/networkextension) API?

I'm using LuLu and hit what looks like a similar [problem](https://github.com/objective-see/LuLu/issues/280#issuecomment-761695395) as your screenshot above shows.

**Comment by zero0ID** [comment]
If the LuLu preferences are set to allow All Apple, should not be a problem with the developer ID checking by Apple and consequently to run the app.
-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


17 Jan 2021, 00:30 by notifications@github.com:

**Comment by kkk669** [comment]
@zero0ID @crcastle Thanks for some information. I've also received a response from Apple. I'll check it along with that.

**Comment by kkk669** [comment]
I understand the way to make DNSecure active on macOS.

1. Select DNSecure
2. Click "..."
3. Click "Make Service Active"
4. Click "Apply"

![IMG_0244](https://user-images.githubusercontent.com/601636/104843949-9b03d300-5910-11eb-8594-4b12fc1512e1.jpeg)

![IMG_0245](https://user-images.githubusercontent.com/601636/104843940-8fb0a780-5910-11eb-8ed1-58d5138cebad.jpeg)

![IMG_0246](https://user-images.githubusercontent.com/601636/104843941-917a6b00-5910-11eb-8796-d73c3c0a4ffd.jpeg)

**Comment by sedony23** [comment]
Great work! Can you share a working binary of the macOS version?

**Comment by kkk669** [comment]
@sedony23 Thanks for your interests, but it's still under development. Could you wait for a while?

**Comment by sedony23** [comment]
Sure, I will wait. I use it on my iPhone and iPad and I'm super happy with it 🙂

**Comment by kkk669** [comment]
I've just submitted the macOS version of DNSecure to the Mac App Store 🎉

Look forward to it!

**Comment by kkk669** [comment]
Because the first version is a Mac Catalyst app, you might feel ugly for macOS. In the future, I will make it a true macOS app in the [macos branch](https://github.com/kkk669/DNSecure/tree/macos).

**Comment by sedony23** [comment]
> I've just submitted the macOS version of DNSecure to the Mac App Store 🎉
> 
> Look forward to it!

Thanks, this ist awesome!
