### ISSUE TITLE
Oblivious DoH protocol

### ISSUE THREAD

**Issue by zero0ID** [kkk669/DNSecure#35]
Would be nice to implement into DNSecure app also the Apple / Cludflare newly developed ODoH protocol.
At the moment seems that such DNS server is provided by Cloudflare only, but other will follow soon. I think.

Here’s how it works:
ODoH wraps a layer of encryption around the DNS query and passes it through a proxy server, which acts as a go-between the internet user and the website they want to visit. Because the DNS query is encrypted, the proxy can’t see what’s inside, but acts as a shield to prevent the DNS resolver from seeing who sent the query to begin with.
Summary by Bruce Schneier

https://blog.cloudflare.com/oblivious-dns/

**Comment by kkk669** [comment]
Thanks for the suggestion.

Unfortunately, DNSecure is just a configuration tool to activate the feature of iOS/iPadOS itself, and protocols (e.g. DoT and DoH) has been implemented in iOS/iPadOS, not in our app. So, if we support the new protocol, we need to wait for Apple to implement that protocol into the future version of iOS/iPadOS.

On the other hand, it may not impossible that we implement Oblivious DNS in DNSecure by ourselves, but in that case, we must use VPN to make it system-wide as CloudFlare's 1.1.1.1 app does. And that's different from the original concept of our app.

So I will close this issue, and wait for Apple at this time. If you find another way, feel free to reopen this issue.

**Comment by zero0ID** [comment]
Thank you for information. As I understood, this protocol is developed by Apple in cooperation with Cloudflare, but maybe not live in current iOS version. Anyway, this protocol needs a proxy placed in front of DNS server to work as intended.

0ID




17 Jan 2021, 14:52 by notifications@github.com:

**Comment by kkk669** [comment]
I'll continue to monitor the latest developments. If I find a way to support it, I will reopen this issue. Thanks.

**Comment by kkk669** [comment]
FYI, iOS/iPadOS 15 and macOS Monterey is going to support Private Relay, which seems to use Oblivious DoH.

https://developer.apple.com/videos/play/wwdc2021/10096/
