### ISSUE TITLE
DoQ

### ISSUE THREAD

**Issue by no0ID** [kkk669/DNSecure#40]
Apparently DNS-over-QUIC can run in iOS as by AdGuard, possible implementation in DNSecure would be nice.

https://adguard.com/en/blog/adguard-4-0-4-for-ios.html

**Comment by kkk669** [comment]
Thank you for the feature request.

DNSecure is just a configuration tool for NEDNSSettingsManager API, in which Apple has implemented DoT and DoH. DNSecure doesn't contain implementations of those protocols, so I don't intend to add support for protocols that are not currently implemented by Apple in iOS, iPadOS, and macOS.
