### ISSUE TITLE
Difference between iOS and iPadOS versions

### ISSUE THREAD

**Issue by no0ID** [kkk669/DNSecure#41]
is there a difference between the two app versions?

With the iPhone cannot connect to a DoT server, the same server with DoH works OK.
The iPad connects the same DoT server without any problem. This is not a new issue, just forgot to report

**Comment by kkk669** [comment]
No, both of them are using the same APIs. Is there another difference between the two (e.g. iPhone is using VPN)?

**Comment by no0ID** [comment]
There is no difference at all, I double checked everything. As everything is equal on my side, hence my question if there is no difference between iOS and iPadOS versions.

**Comment by kkk669** [comment]
Could you tell me your configuration of DNSecure? And, what is your iPhone's primary network interface, e.g. Wi-Fi or Cellular?

**Comment by no0ID** [comment]
Here is the configuration, the interface on both is WiFi. When selecting cellular on iPhone nothing changes, still not working.

**Comment by kkk669** [comment]
Could you please tell me the full configuration of the server that you tried to use on DNSecure? And also on-demand rules are included if you are using them. If you don't want to transcribe it, you can post screenshots of DNSecure.

**Comment by no0ID** [comment]
Strange, I attached the screenshot in my previous reply by email but seems that wasn't processed by GitHub.
No on demand rules applied.

![B5AE5AEA-A3E2-4527-9230-D5656EEA5D95](https://user-images.githubusercontent.com/79188024/108817826-c7b6a480-75b8-11eb-9975-ad0676bc207b.png)

**Comment by kkk669** [comment]
Thank you.

> No on demand rules applied.

In your screenshot, it looks like an on-demand rule named "New Rule" is created, which is correct?

And then, it seems that you are having problem only with your iPhone but not with your iPad, so can you post a screenshot of your iPhone?

**Comment by no0ID** [comment]
New Rule is empty as it is the row Probe URL.
I ticket Add Rule and don't know how to delete it. My iPad is WiFi only.

<img width="1163" alt="Screenshot 2021-02-23 at 09 38 50" src="https://user-images.githubusercontent.com/79188024/108819729-7cea5c00-75bb-11eb-874b-965dfa3de460.png">

**Comment by kkk669** [comment]
How about your iPhone?

FYI, you can delete it by following steps on the first screenshot's screen.

1. Tap Edit button on the top-right side of the on demand rules section
2. Tap ⛔️ button
3. Tap Delete button

Or, you can dot it by another steps.

1. Swipe from right to left on the cell of the rule

Video: ![](https://user-images.githubusercontent.com/601636/108820462-91504800-75ff-11eb-891e-c1d50e21f130.MP4)

**Comment by no0ID** [comment]
Thank you for the deleting hint. Attached the iPhone screenshot and as I cannot extend the screenshot down to bottom, the ON DEMAND RULES status is Ad New Rule.

<img width="375" alt="Screenshot 2021-02-23 at 10 02 45" src="https://user-images.githubusercontent.com/79188024/108822170-fdf72280-75be-11eb-806a-c2c91d47582c.png">

**Comment by kkk669** [comment]
Thank you, but I would like to know your DoT configuration which you said your iPhone cannot connect to.

And by the way, how did you determine that it could not connect to the server?

**Comment by no0ID** [comment]
I uploaded the iPhone printscreen to GitHub.
And how I determined that DoT is not working on iPhone? Well it cannot connect to internet.

**Comment by kkk669** [comment]
The screenshot you uploaded was the configuration of DoH. You said DoH worked on your iPhone, didn't you? I'd like to know the configuration that didn't work because I may be able to reproduce the problem. If I can reproduce it on my device, I can investigate it.

**Comment by no0ID** [comment]
Sorry, I was in hurry.
Yes, the DoH works on iPhone. Related to this, the correct DoT screenshot, is valid what I wrote above.

<img width="375" alt="DoT" src="https://user-images.githubusercontent.com/79188024/108863543-99a18680-75f1-11eb-951e-e8e5a4229790.png">

**Comment by kkk669** [comment]
@no0ID Thank you for sharing your configuration. Probably, the Server Name is wrong because the one you specified is starting with https. And also, you can delete the empty cell of servers by the same way as [this](https://github.com/kkk669/DNSecure/issues/41#issuecomment-784012987).

**Comment by no0ID** [comment]
Sorry, had no idea that DoT is not using https.
When inputed: unicast.uncensoreddns.org everything works fine also on iPhone.

Thank you for the extended support!

**Comment by kkk669** [comment]
You're welcome!
