### ISSUE TITLE
Cannot edit on-demand rules

### ISSUE THREAD

**Issue by itsByte** [kkk669/DNSecure#54]
Editing anything inside an on-demand rule causes the view to close itself 

Steps to reproduce:
- Open a server’s details
- Add a new on-demand rule
- Tap on it and make any modification

Specifications:
iOS Version: 16.1
Device: iPhone 12 Mini
App version: 1.4.0 (Apple Store)

**Comment by kkk669** [comment]
I can replicate that issue. Thank you for your feedback.

**Comment by kkk669** [comment]
The issue also occurs in macOS 13 (Mac Catalyst).

**Comment by kkk669** [comment]
I fixed the issue in DNSecure 1.4.1, and I've submitted both the iOS app and the macOS app to the App Store Review. I hope that these new versions will be released to the TestFlight and the App Store in a few days.
