### ISSUE TITLE
Blank screen when editing rule

### ISSUE THREAD

**Issue by aednichols** [kkk669/DNSecure#61]
iOS 16.4.1, iPhone 12 mini

Steps to reproduce:

1. Select a server, create a new rule
2. Enter the rule-edit screen
3. Add SSID
4. Type 1 character in the SSID text field

Expected result:
- Can enter SSID

Actual result:
- Screen goes blank:

![IMG_9532 (1)](https://user-images.githubusercontent.com/1087943/233801355-7a930035-a7b6-4f0f-b44f-e84749990a98.png)

**Comment by kkk669** [comment]
I can reproduce the issue. Thanks for reporting.

**Comment by kkk669** [comment]
I've submitted 1.4.3 (17) to TestFlight. This version will be available on TestFlight shortly. I hope it will resolve your issue.

**Comment by kkk669** [comment]
> I did notice there is still some lag on each keystroke but it's serviceable.

I'm working on it in #63. I hope this will be included in the 1.4.3 release.
