### ISSUE TITLE
Selected DNS doesn’t persist when closing and reopening app

### ISSUE THREAD

**Issue by therealparmesh** [kkk669/DNSecure#72]
https://github.com/kkk669/DNSecure/assets/7146141/38db73f4-1516-420f-8414-8110e29729a1

**Comment by therealparmesh** [comment]
Please see video for details.

**Comment by kkk669** [comment]
Thank you for reporting it. Could you provide your OS version?

**Comment by therealparmesh** [comment]
iOS 17.1.2

**Comment by kkk669** [comment]
I can reproduce this issue. It occurs only if you haven't ever added or changed server configurations.

I'll try to fix it in a few days.

**Comment by kkk669** [comment]
@therealparmesh 

I fixed the issue in 1.4.5. That version will be released to TestFlight soon. If it's released, could you please test it and make sure that the issue is fixed?

**Comment by therealparmesh** [comment]
It works! Thanks for your great work.

**Comment by kkk669** [comment]
Thank you. I'll release it to the App Store.
