### ISSUE TITLE
Include New Instructions for MacOS Sonoma+

### ISSUE THREAD

**Issue by WingofaGriffin** [kkk669/DNSecure#75]
Not a huge difference, but the new MacOS Network page functions different enough to make the current instructions not relevant. Screenshots would be helpful too.

**Comment by kkk669** [comment]
I added instructions for macOS 13 or later in #76. I'll release it as soon as possible. Thank you for letting me know.

**Comment by kkk669** [comment]
DNSecure 1.4.4 has been released to the Mac App Store.
