### ISSUE TITLE
Unable to add dns ip address

### ISSUE THREAD

**Issue by aalmenar** [kkk669/DNSecure#8]
The ui when adding an IP address doesn’t allow to set the dots in an ip address
![5DB4B107-46C6-49F7-9FFC-E6149D72EEF9](https://user-images.githubusercontent.com/161029/96039658-511ad500-0e69-11eb-9c83-6aa999aff560.jpeg)

**Comment by kkk669** [comment]
Thank you for reporting the issue. I'll fix it ASAP.

**Comment by kkk669** [comment]
I plan to release to TestFlight first, and then to App Store, both in a few days.

If you want to join the beta testing, you can do from https://testflight.apple.com/join/A8GwCnq8.

**Comment by kkk669** [comment]
DNSecure 1.0.2 is now available on the App Store.
