### ISSUE TITLE
Feature: disable dns while on certain wifi networks

### ISSUE THREAD

**Issue by aalmenar** [kkk669/DNSecure#9]
It could be nice to disable encrypted dns behavior while connected to certain WiFi’s, also a whole new level would be to use certain profiles on encrypted dns depending on the wifi you’re currently connected.

**Comment by kkk669** [comment]
I'll consider that. Thanks for suggesting!

**Comment by kkk669** [comment]
I've started working on it.

**Comment by aalmenar** [comment]
Nice WIP looks nice and also has MacOS support in it. 😁

**Comment by kkk669** [comment]
@aalmenar I've been experimenting with Mac Catalyst since the beginning, but it hasn't worked well yet. So, macOS support itself is still a long way off, but this is preparation for that.

**Comment by aalmenar** [comment]
I've been playing with the code, and i think it would be kind of easier to have something like:

Add Networks to exclude. 

Add domains to exclude.

Without all the rule management available to keep it simple.

Thoughts?

**Comment by kkk669** [comment]
@aalmenar Thanks for your suggestion. In my opinion, iOS's settings app should have the same feature as DNSecure has. However, it doesn't, so I want DNSecure to cover everything iOS API can do. I understand that fewer choices are easier for users to use, but your suggestion limits the functionality, so it's not desirable for me.
